### ISSUE TITLE
Will you be updating this to support Floating UI?

### ISSUE THREAD

**Issue by spsaucier** [lxsmnsyc/solid-popper#1]
[Floating UI](https://floating-ui.com/) is a tiny library and is the next version of Popper, so it'd be great to be able to migrate to it.

**Comment by lxsmnsyc** [comment]
Interesting. I never saw this before. If this is supposed to be the successor for Popper and is now the recommended way, I'll probably support this, or make a separate package for Floating UI and keep solid-popper as is. I'll check this first and see what's the best action for this. Thanks for the visibility.

**Comment by lxsmnsyc** [comment]
I've created a separate project: https://github.com/lxsmnsyc/solid-floating-ui

**Comment by gBasil** [comment]
Could you consider putting some text along the lines of "For Floating UI, check out [`solid-floating-ui`](https://github.com/lxsmnsyc/solid-floating-ui)" into the README?
